name: VIDER CORE RUN

on:
  workflow_dispatch:

jobs:

  run-vider:

    runs-on: ubuntu-latest

    steps:

    - name: Download Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Run Vider
      run:
        python vider_core.py
