from fastapi import FastAPI
import uvicorn
import json
import os
from datetime import datetime


app = FastAPI()

MEMORY = "vider_v6_memory.json"


# =========================
# MEMORY
# =========================

def load_memory():

    if not os.path.exists(MEMORY):

        return []

    with open(
        MEMORY,
        "r",
        encoding="utf-8"
    ) as f:

        return json.load(f)



def save_memory(data):

    with open(
        MEMORY,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            data,
            f,
            ensure_ascii=False,
            indent=4
        )



def remember(task,result):

    mem = load_memory()

    mem.append({

        "time":
        str(datetime.now()),

        "task":
        task,

        "result":
        result

    })

    save_memory(mem)



# =========================
# AGENT BRAIN
# =========================

def agent_think(task):

    return {

        "goal":
        task,

        "plan":
        [
            "วิเคราะห์",
            "เลือกเครื่องมือ",
            "ทำงาน",
            "ตรวจผล"
        ]

    }



# =========================
# TOOL SYSTEM
# =========================

def tool_create_file():

    with open(
        "vider_agent_output.py",
        "w",
        encoding="utf-8"
    ) as f:

        f.write(
"""
print("Generated by VIDER Agent")
"""
        )

    return "สร้างไฟล์สำเร็จ"



# =========================
# AGENT CORE
# =========================

def run_agent(task):

    brain = agent_think(task)

    action = tool_create_file()


    result = {

        "brain":
        brain,

        "action":
        action,

        "status":
        "completed"

    }


    remember(
        task,
        result
    )


    return result



# =========================
# API
# =========================

@app.get("/")
def status():

    return {

        "system":
        "VIDER v6",

        "status":
        "online"

    }



@app.post("/agent")
def command(data:dict):

    return run_agent(
        data["task"]
    )



# =========================
# START
# =========================

if __name__=="__main__":

    print(
        "VIDER v6 ONLINE"
    )

    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000
    )
